name: Feature Request
description: Suggest a new feature for ColorBrew
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?

  - type: textarea
    id: proposed-api
    attributes:
      label: Proposed API
      description: How would you expect to use this feature?
      render: python
